name: r_rise
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.1.1
  - rise=5.7.1
  - r-base=4.4.3
  - python=3.12.11
  - r-irkernel=1.3.2
  - pip=25.2
  - r-broom=1.0.9
  - r-ggfortify=0.4.19
  - ipykernel=6.29.5
  - notebook=6.5.7
  - r-tidyverse=2.0.0
  - r-palmerpenguins
  - r-ggthemes
  - r-mass
  - r-caret
  - r-nycflights13
  - r-islr2
  - r-mgcv
  - r-car
