name: r_rise
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.5
  - jupyter=1.1.1
  - notebook=6.5.7
  - pip=25.2
  - python=3.12.11
  - r-base=4.4.3
  - r-broom=1.0.9
  - r-ggfortify=0.4.19
  - r-irkernel=1.3.2
  - r-tidyverse=2.0.0
  - rise=5.7.1

